### ISSUE TITLE
Set retry count for scheduled event to 0

### ISSUE THREAD

**Issue by jakobbraun** [exasol/cloudwatch-adapter#21]
The events must not retry, since this could lead to duplicate reporting

**Comment by jakobbraun** [comment]
Basically this should be as simple as adding 

```yml
RetryPolicy:
  MaximumRetryAttempts: 0
  MaximumEventAgeInSeconds: 60
```

to the `template.yaml`. But then publish fails due to a bug in sam: https://github.com/aws/serverless-application-model/issues/1931
